In [1]:
# 주피터 노트북 환경설정
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

from IPython.display import set_matplotlib_formats
set_matplotlib_formats("retina")

from IPython.core.display import display, HTML
# display(HTML("<style>.container { font-weight: bold !important; font-family:'Malgun Gothic' !important;}</style>"))
display(HTML("<style>.container { font-weight: bold !important;}</style>"))
display(HTML("<style>.container { width: 98% !important; }</style>"))


In [2]:
# 모듈 임포트 
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
#  한글글꼴로 변경
plt.rcParams['font.size'] = 12.0
plt.rcParams['font.family'] = 'Malgun Gothic'

# Skitlearn의 Scaling 
## StandardScaler 
- 평균이 0이고 분산이 1인 정규분포 형태로 변환

```
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(Data)
Data_scaled = scaler.transform(Data)
```

## MinMaxScaler

- 데이타값을 0과 1 사이의 범위값으로 변환한다. 음수값이 있으면 -1에서 1값으로 변환한다 

```
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(Data)
Data_scaled = scaler.transform(Data)
```

### iris 붓꽃 데이터셋으로 스케일링 실습하기

In [3]:
from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris.data, columns=iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
# 스케일링
from sklearn.preprocessing import StandardScaler

# 스케일러 생성
scaler = StandardScaler()

# 스케일러 데이터 입력
scaler.fit(iris_df)

# transform() 메서드를 이용해서 스케일 된 데이터를 별도 변수에 저장
# 넘파이 배열
iris_scaled = scaler.transform(iris_df)

type(iris_scaled)

numpy.ndarray

In [5]:
# 데이터프레임 형태로 저장하기
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns=iris.feature_names)
print('feature들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산 값')
print(iris_df_scaled.var())

iris_df_scaled.head(5)

feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

In [6]:
# y타겟값 생성하기
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


In [7]:
# X 입력 데이터 => 스케일링된 데이터 프레임
# y 타겟 데이터 => 넘파이 배열
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris_df_scaled, iris_label, test_size=0.2, random_state = 11)

In [8]:
len(X_train), len(X_test)

(120, 30)

In [9]:
X_train[:3]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
120           1.280340          0.328414           1.103783          1.448832
122           2.249683         -0.592373           1.672157          1.053935

In [10]:
# KNeighborClassifier로 학습하기
from sklearn.neighbors import KNeighborsClassifier
model_kn = KNeighborsClassifier()

# 학습하기
model_kn.fit(X_train, y_train)

KNeighborsClassifier()

In [11]:
model_kn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [12]:
# 평가
model_kn.score(X_train, y_train), model_kn.score(X_test, y_test)

(0.9666666666666667, 0.9333333333333333)

In [13]:
model_kn.predict(X_test)

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [14]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [15]:
from sklearn.metrics import accuracy_score

print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, model_kn.predict(X_test))))

예측 정확도: 0.9333


### MinMaxScaler 적용하면 차이가 있을까?

- 데이터 값을 0과 1사이의 범위 값으로 변환한다. 음수값이 있으면 -1에서 1값으로 변환

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
# 데이타셋 생성 
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature들의 최소 값')
print(iris_df.min())
print('\nfeature들의 최대 값')
print(iris_df.max())
print('\n'*2)

# 스케일러 객체 생성 
scaler = MinMaxScaler()
# 데이타 입력 
scaler.fit(iris_df)
# 변형된 데이타를 변수에 저장 => 넘파이 배열화 
iris_scaled2 = scaler.transform(iris_df)
# print(iris_df_scaled2) 

# 데이타프레임 화 
iris_df_scaled2 = pd.DataFrame(data=iris_scaled2, columns=iris.feature_names)
print('feature들의 최소 값')
print(iris_df_scaled2.min())
print('\nfeature들의 최대 값')
print(iris_df_scaled2.max())


feature들의 최소 값
sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64

feature들의 최대 값
sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64



feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [18]:
iris_df_scaled.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

In [19]:
# y 라벨 ㅐㅅㅇ성
iris_label = iris.target

# 학습데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(iris_df_scaled2, iris_label,
                                                    test_size=0.2, random_state=11)

In [20]:
# 학습기를 통한 학습
model_kn = KNeighborsClassifier()

model_kn.fit(X_train, y_train)

KNeighborsClassifier()

In [21]:
# StandardScaler() 적용시 값
# (0.96666666667, 0.9333333333)

In [22]:
model_kn.score(X_train, y_train), model_kn.score(X_test, y_test)

(0.975, 0.9333333333333333)

In [23]:
# 테스트 데이터의 스코어 점수는?
model_kn.score(X_test, y_test)

0.9333333333333333

## 스케일링 변환 시 주의사항

- 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리한다. 
- 전체 데이터 스케일링 변환이 여의치 않다면 테스트 데이터 변환시에는 fit()을 적용하지 않고 학습 데이터로 이미 fit()된 Scale 객체를 이용해 Transform()으로 변경하기

In [24]:
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

print(train_array)
print()
print(test_array)
print()
print(train_array.ndim,test_array.ndim )
print()
print(train_array.shape,test_array.shape )

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]

2 2

(11, 1) (6, 1)


In [25]:
# 스케일러 생성 
scaler = MinMaxScaler()
# 입력 데이타로 스케일링
scaler.fit(train_array)

# 변환 데이타를 변수에 저장 
train_scaled = scaler.transform(train_array)
print(train_scaled)
print('='*50)

# fit() 하지 말고 transform() 적용 
# scaler.fit(test_array)
test_scaled1 = scaler.transform(test_array)
print(test_scaled1)
print('='*50)

[[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]
 [0.7]
 [0.8]
 [0.9]
 [1. ]]
[[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]]
