# 넘파이 배열의 자료형 지정하기
```
배열명2 = 배열명1.astype(자료형)
자료형 = np.float64, np.int32
```

In [1]:
import numpy as np

In [2]:
# 정수형 3행 3열 만들기
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [3]:
# 실수형 3행 3열 만들기
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [5]:
# 문자열형 3행 3열 만들기
# astype('<U5')를 통해서 정수형 만들기
matrix= np.arange(1,10).reshape(3,3).astype('<U5')
matrix

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U5')

In [6]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True, False])
matrix2, matrix2.dtype

(array([ True, False,  True,  True, False]), dtype('bool'))

In [7]:
# 논리형에서 정수형으로 변환 True = 1, False = 0
matrix2.astype(int)

array([1, 0, 1, 1, 0])

In [8]:
# 정수형에서 문자형으로 변환 ''안에 True, False
matrix2.astype('U5')

array(['True', 'False', 'True', 'True', 'False'], dtype='<U5')

In [10]:
# 문자열 숫자 => 일반 정수나 실수형으로 변환하기
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3.astype(float), matrix3.astype(float).dtype

(array([3.14, 5.5 , 0.78]), dtype('float64'))

In [11]:
matrix4 = np.array(['3', '5', '0'])
matrix4.astype(int)

array([3, 5, 0])

# 넘파이 배열의 인덱싱

```
넘파이 배열명[Index]

넘파이 배열명 [i,j] => i행 j열
넘파이 배열명 [i][j] => i행 j열
```

In [15]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)
print(matrix_a)
print(matrix_b)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
# 첫 요소와 마지막 요소
print(matrix_a[0])
print(matrix_a[-1])

0
9


In [20]:
# 2차원에서 1행 1열
print(matrix_b[0,0])
print(matrix_b[0][0])
# 마지막 행의 마지막열
print(matrix_b[-1,-1])
print(matrix_b[-1][-1])

0
0
11
11


In [21]:
# matrix_b에서3행 1열의 값 변경하기
print(matrix_b)
matrix_b[2,0] = 100
print(matrix_b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   2   3]
 [  4   5   6   7]
 [100   9  10  11]]


# 넘파이 배열의 슬라이싱
## 1차원

```
넘파이 배열명 [start:end:step] start인 부분부터 end인 부분까지 step으로
넘파이 배열명[start:end] start인 부분부터 end까지
넘파이 배열명[start:]  start인 부분부터 끝까지
넘파이 배열명[:end]  처음부터 end인 부분까지
-기호는 역순으로 표시
넘파이 배열명 [::-1]
```

In [23]:
matrix_c = np.arange(0, 101, 10)
matrix_c

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [31]:
print(matrix_c[1:7:2]) # 인덱스1부터 7까지 2씩 건너서
print(matrix_c[:7]) # 처음부터 인덱스 7까지
print(matrix_c[5:]) # 인덱스 5부터 끝까지
print(matrix_c[::2]) #전체에 대해서 2칸씩 건너 뛰기
print(matrix_c[::-1]) # 역순

[10 30 50]
[ 0 10 20 30 40 50 60]
[ 50  60  70  80  90 100]
[  0  20  40  60  80 100]
[100  90  80  70  60  50  40  30  20  10   0]


## 2차원

```
넘파이 배열명 [start1:end1:step1, start2:end2:step2]
- 역순으로 표시
넘파이 배열명 [::-1, ::]
넘파이 배열명 [::, ::-1]
```

In [33]:
# 5행 5열 만들기
matrix_d = np.arange(1,26).reshape(5,5)
matrix_d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
print(matrix_d[0,::]) # 1행만 출력하기
print(matrix_d[0:2, ::]) # 1,2행출력으로 모든 컬럼
print(matrix_d[::,2:4]) # 모든행, 23컬럼 출력하기
print(matrix_d[0:3, 0:2]) # 1,2,3행 출력, 1,2컬럼 출력

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [46]:
print(matrix_d[::2, ::]) # 홀수번째 행만 출력
print(matrix_d[::, 1::2]) # 짝수 열만 출력 1번째부터 시작해서 2step으로
print(matrix_d[1::2, 1::2]) # 짝수번째행 + 짝수번째 열 출력

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]
[[ 7  9]
 [17 19]]


In [49]:
print(matrix_d[::-1, ::]) # 행인덱스를 기준으로 역순
print(matrix_d[::, ::-1]) # 열 인덱스를 기준으로 역순
print(matrix_d[::-1, ::-1]) # 행과 열 모두 역순

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]
[[25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


# 전치행렬
```
넘파이배열 마지막에 .T를 붙인다.
행이 열이되고 열이 행이되는것
```

In [50]:
# 3행2열 넘파이 배열
matrix_e = np.arange(1,7).reshape(3,2)
matrix_e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
# 3행 2열 ===>> 2행 3열
matrix_e.T

array([[1, 3, 5],
       [2, 4, 6]])

# 넘파이 배열의 난수값 지정하기
## 난수로 구성된 넘파이 배열 생성
```
np.random
np.random.randint(start, end, n) #정수로 구성된 난수 생성
np.random.randint(start, end, (i,j)) 정수로된 배열 생성
```

In [58]:
print(np.random.randint(1, 100, 2)) # 1 ~ 100까지의 정수중 2개
print(np.random.randint(1,10,10)) # 1 ~ 10까지의 정수중 10개
print(np.random.randint(1,10,(5,2))) # 1~10까지의 숫자중 10개를 5행 2열형식으로

[18 81]
[6 6 9 4 2 4 8 7 5 3]
[[1 9]
 [3 4]
 [1 9]
 [4 3]
 [3 4]]


## 섞기 
``` 
np.random.shuffle(넘파이 배열)
```

In [60]:
matrix_f = np.arange(1,11)
print(matrix_f)
np.random.shuffle(matrix_f) # np.random.shuffle을 사용해서 섞기
matrix_f

[ 1  2  3  4  5  6  7  8  9 10]


array([ 4,  9,  2,  8,  5,  6,  3, 10,  7,  1])

In [61]:
# 1~ 46까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호 생성하기
np.random.randint(1, 47, 6)

array([ 8, 41, 30, 27, 16, 12])

In [64]:
# 1~ 46까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호 생성하기
matrixlotto = np.arange(1,47)
matrixlotto
np.random.shuffle(matrixlotto)
lotto_num = matrixlotto[:6]
lotto_num

array([ 2, 16, 45, 10, 22,  3])

## 실수난수

```
matrix1 = np.random.randn(n)
matrix2 = np.random.randn(i,j)
```

In [65]:
matrix1 = np.random.randn(10)
matrix2 = np.random.randn(4,4)

In [66]:
matrix1

array([-0.38715281, -0.79740213, -1.25212368, -0.36866331, -0.68807706,
       -1.10197785, -1.89672438, -2.31251119,  0.83621455,  0.50069324])

In [67]:
matrix2

array([[ 0.57649042, -0.56106824, -1.83775906,  0.81647492],
       [ 0.99658115, -0.65909955, -1.04171651,  0.97071268],
       [ 0.65727231, -0.41194943, -0.33433592, -0.30263115],
       [-0.30463249, -0.45696997,  0.48167344, -0.01308976]])

In [69]:
# 최대값, 최소값 
matrix1.max(), matrix1.min()

(0.8362145496429086, -2.3125111934041245)

# 집계함수와 정렬에서의 축 

```
2차원에서 집게함수(sum, mean)
axis = 0아니면 1
np.sum(넘파이배열명, axis = 0/1)
np.mean(넘파이배열명, axis=0/1)
np.sort(넘파이배열명, axis=0/1)
```

In [70]:
# 정수 난수로 구성된 5*5
m1 = np.random.randint(1, 50, (2,5))
m1

array([[40,  8, 34, 30, 38],
       [33, 23, 26,  5,  8]])

In [71]:
# axis = 0이면 열로 더하기
np.sum(m1, axis=0)

array([73, 31, 60, 35, 46])

In [72]:
# axis = 1이면 행으로 더하기
np.sum(m1, axis=1)

array([150,  95])

In [73]:
# 1행의 합계는??
np.sum(m1[0,:])

150

In [76]:
np.sum(m1, axis=1)[0]

150

In [77]:
np.max(m1, axis=1)

array([40, 33])

## np.sort()

In [78]:
# 정수, 난수로 구성된 2*5
m2 = np.random.randint(1,50, (4,3))
m2

array([[ 5, 37,  9],
       [31, 33, 21],
       [33, 36, 11],
       [41, 44,  8]])

In [79]:
# axis = 0이면 세로방향으로 값을 기준으로 오름차순 정렬
m2 = np.sort(m2, axis= 0)
m2

array([[ 5, 33,  8],
       [31, 36,  9],
       [33, 37, 11],
       [41, 44, 21]])

In [80]:
# axis = 1이면 가로방향으로 값을 기준으로 오름차순 정렬
np.sort(m2, axis=1)

array([[ 5,  8, 33],
       [ 9, 31, 36],
       [11, 33, 37],
       [21, 41, 44]])

In [82]:
# 내림차순으로 다시 정렬
m2[::-1, ::]

array([[41, 44, 21],
       [33, 37, 11],
       [31, 36,  9],
       [ 5, 33,  8]])

## 인덱스 소팅

```
np.argsort(배열명, axis=0/1)
argsort = argumentsort로써 인덱스가 반환이 된다.

넘파이 배열 [np.argsort 배열] => 오름차순한 결과
```

In [83]:
# 순서에 맞게 인덱스가 Sort된다.
x = np.array([3,1,2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [85]:
x[np.argsort(x)] # x의 값에 대해서 argsort한 순서대로 내보내기

array([1, 2, 3])

In [86]:
np.sort(x)

array([1, 2, 3])

## 넘파이 배열의 추가와 삭제

```
np.insert(배열명, 위치인덱스, 값, axis=0/1)
2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경된 후 값이 삽입된다.
값은 리스트나 특정 숫자
```

In [89]:
mm1 = np.arange(1,11)
# 1차원인 경우는 axis 불필요
mm1 = np.insert(mm1, 0, 100) # 0번째 인덱스에 100값 삽입
mm1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [91]:
# -1이면 맨 마지막 자리에서 한 자리 앞으로 삽입이 된다. 
# 끝에서 2번째 자리 
np.insert(mm1, -1, 500)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [92]:
# 끝에서 3번째 자리
np.insert(mm1, -2, 500)

array([100,   1,   2,   3,   4,   5,   6,   7,   8, 500,   9,  10])

In [93]:
# 제일 끝자리 0부터 시작을 하여서 len을 하면 +1로써 마지막으로 들어간다.
np.insert(mm1, len(mm1), 500)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [94]:
mm2 = np.arange(1,10).reshape(3,3)
mm2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
# 2차원인데 axis를 넣지 않아서 1차원으로 변경이 되었다.
# 기존 mm2는 1부터 9까지의 3행3열 2차원 But 
np.insert(mm2, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [97]:
# 1행으로 [100, 100, 100]생성해서 삽입
np.insert(mm2, 0, 100, axis=0) # 첫행에 가로행으로 삽입

array([[100, 100, 100],
       [  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [99]:
np.insert(mm2, 0, 100, axis=1) # 첫 열에 100 삽입

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [100]:
np.insert(mm2, 0, [100, 200, 300], axis=1) # 첫 열에 100,200,300 삽입

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [102]:
np.insert(mm2, 3, [100, 200, 300], axis=1) # 마지막 열에 100,200,300 삽입


array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [105]:
# 리스트로 삽입 - 마지막 컬럼으로 삽입
# 배열명 .shape[1] 컬럼길이
# mm2.shape[1] =3
np.insert(mm2, mm2.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [106]:
# 1행 삭제
np.delete(mm2, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [107]:
# 첫번째 원소만 삭제
# 2차원 배열이 1차원으로 변경
np.delete(mm2, 0)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
# 1열 삭제
np.delete(mm2, 0, axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

## Stack 
```
vstack --> 겹대괄호 사용 행으로 합치기, 2차원으로 지정
hstack --> 겹대괄호 사용 열로 합치기
```

In [110]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b))) # 행으로 합치기
print(np.hstack((a,b))) # 열로 합치기 

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [111]:
# 2차원 배열 재구성
np.vstack((a,b)), np.vstack((a,b)).shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [112]:
# 열을 기준으로 병합
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

## concatenate() 합치기 
```
But 무조건 2차원이어야 한다.
```

In [113]:
c = np.array([[1,2,3]])
# ndim을 통해서 차원확인, shape를 통해서 모양확인
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [114]:
d = np.array([[4,5,6]])
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [116]:
# 2차원 행렬을 행으로 합치기
np.concatenate((c,d), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
# 2차원 행렬을 열으로 합치기
np.concatenate((c,d), axis=1)

array([[1, 2, 3, 4, 5, 6]])