# 불린 마스크

```
조건절의 결과는 True, False로 반환
True인 결과의 데이터프레임 반환
```

In [2]:
import numpy as np

In [3]:
matrix = np.arange(1,21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
# 넘파이 배열에 비교 연산자 적용 ====> True/False 값 반환
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
# True는 1값, False는 0값으로 갯수를 반환
(matrix > 10).sum()

10

In [6]:
# 넘파이 배열 [조건절] => 조건절을 만족하는 실제값 반환
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
# 1 ~ 100 사이의 숫자중에서 랜덤하게 30개를 추출하여 랜덤하게 넘파이 배열을 생성
# 30보다 크거나 70보다 작은 숫자를 추ㅜㅊㄹ
quiz = np.random.randint(1, 101, 30) # 1부터 100까지의 30개 랜덤한 숫자
quiz[(30 < quiz) & (quiz < 70)]

array([58, 40, 56, 44, 58, 66, 41, 64, 45, 52, 57, 58])

In [9]:
# 30보다 크고 70보다 작은 갯수는 12개
((quiz > 30) & (quiz < 70)).sum()

12

In [10]:
# 10보다 작거나 90보다 큰 값 
quiz[(quiz < 10) | (quiz > 90)]

array([ 8, 93, 96,  4,  6])

## 팬시 인덱싱
```
넘파이 배열1 [넘파이배열2]
넘파이 배열2 => 인덱스 역활
```

In [11]:
matrix3 = np.random.randint(1, 100, 30)
matrix3

array([59, 55, 44, 28, 89, 16, 21,  3, 89, 72, 86, 62, 35, 59, 21, 57, 12,
       66, 26, 92, 92, 12, 79, 55, 89, 37, 91, 17, 83, 31])

In [13]:
# matrix4는 팬시인덱싱 역활로 dtype이 int여야 한다.
# 필터링 인덱스 => 팬시 인덱싱
# 인덱스를 통하므로 정수여야 한다.
matrix4 = np.array([0,2,3,10,20,-1])
matrix4

array([ 0,  2,  3, 10, 20, -1])

In [14]:
# 인덱스 
matrix3[matrix4]

array([59, 44, 28, 86, 92, 31])

In [15]:
matrix5 = np.random.randint(1, 100, 30).reshape(6,5)
matrix5

array([[95,  1, 56, 51, 67],
       [12, 83, 26, 13, 40],
       [ 3, 95, 27, 68, 72],
       [ 4, 55, 82, 20, 86],
       [68, 79, 73, 21, 45],
       [16, 39, 34, 82, 81]])

In [16]:
matrix5[0,0], matrix5[0][0]

(95, 95)

In [17]:
# matrix4에서 1행 1열 값과 6행 5열 값을 추출
matrix5[2,2], matrix5[-1,-1]

(27, 81)

In [18]:
matrix6 = [0,1]
matrix7 = [[0,0], [1,1], [3,2]]

In [19]:
# 배열 이름 [[i1, i2, i3....], [j1,j2,j3]]
# [i1, j1], [i2, j2], [i3,j4].....
matrix5[[0,1,2], [0,1,2]]

array([95, 83, 27])

In [20]:
# 별도 배열로 정의하려면 모두 튜플로 정의한다.
fancy = ((0,1,2,3,4), (0,1,2,3,4))
matrix5[fancy]

array([95, 83, 27, 20, 45])

In [22]:
# 대각선 값 추출하기 
matrix5[[0,1,2,3,4], [0,1,2,3,4]]

array([95, 83, 27, 20, 45])

In [24]:
# 대각선 값 추출하기
fancy = [[0,1,2,3,4], [0,1,2,3,4]]
matrix5[fancy]

c:\Users\TFG5076XG\anaconda3\envs\lima\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  This is separate from the ipykernel package so we can avoid doing imports until


array([95, 83, 27, 20, 45])

# Where 함수 
```
np.where(조건식) => 조건식을 만족하는 인덱스 반환
np.where(조건식, T, F)
=> 조건식을 만족하면 T값 그렇지 않다면 F가 실행

배열 [np.where(조건식)]
=> 조건식을 만족하는 실제 배열값이 반환
```

In [25]:
a = np.arange(10)
# array([0,1,2,3,4,5,6,7,8,9])
np.where(a < 5, a, 10*a)
# a<5이면 a로 출력하고 아니면 10*a로 출력하라

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [26]:
np.where(a < 5)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [27]:
a = np.arange(20, 31)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [28]:
# 인덱스로 반환이 된다.
np.where(a < 25)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [29]:
np.where(a < 25, a, 10 * a)

array([ 20,  21,  22,  23,  24, 250, 260, 270, 280, 290, 300])

In [30]:
# a[]안에 넣게 되면 np.where(a < 25)가 인덱스 역활을 해주어서 실제값이 반환된다.
a[np.where(a<25)]

array([20, 21, 22, 23, 24])

# 외부파일 연동하기
```
배열명 = np.loadtxt('파일경로', delimeter = '구분자', dtype=데이터형)
```

In [32]:
rating = np.loadtxt('data/ratings.dat', delimiter='::', dtype = np.int64)
rating

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [33]:
rating.shape, rating.ndim, rating.dtype

((1000209, 4), 2, dtype('int64'))

In [35]:
# 처음부터 3행까지, 모든열
rating[:3, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968]], dtype=int64)

In [36]:
# 3열의 평점의 평균은?
rating[:, 2].sum(),rating[:3, :].mean() 

(3582313, 244575634.91666666)

In [38]:
#사용자 수?
# np.unique()를 통해서 unique값 확인하기 
np.unique(rating[:, 0]).size

6040

In [39]:
# rating에서 id가 2인사람들
user2 = rating[rating[:,0] == 2]
user2[:5, :]

array([[        2,      1357,         5, 978298709],
       [        2,      3068,         4, 978299000],
       [        2,      1537,         4, 978299620],
       [        2,       647,         3, 978299351],
       [        2,      2194,         4, 978299297]], dtype=int64)

In [42]:
# id가 2인 사람들의 평균
print(user2[:, 2].mean())
f'user id 가 2인 사람의 평점의 평균은? {user2[:, 2].mean():.2f}'

3.7131782945736433


'user id 가 2인 사람의 평점의 평균은? 3.71'

## 파일 저장하기
```
-파일저장
np.savetxt('파일경로', 배열이름, fmt='포맷형식', delimiter='구분자')
```

In [43]:
# 100개의 데이터만 저장 output이라는 폴더 만들고 안에 csv파일 형태로 저장
rating100 = rating[:100, :]
len(rating100)

100

In [ ]:
# np.savetxt('파일경로', 배열이름, fmt = '포맷형식', delimeter='구분자')
# 포맷형식에서 %,2f는 소수점 2자리깢
import os 
os.mkdir('output')
np.savetxt('output/rating100.csv', rating100, fmt='%d', delimiter=',')