# 넘파이 배열 생성 

```
np.array(리스트)
ndim : 차원반환(int)
size : 전체 길이 반환(int)
shape : 구조 반환(tuple)
```

In [3]:
import numpy as np

In [1]:
# 1차원 리스트 
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [8]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원은? {myArr.ndim}')
print(f'구조는? {myArr.shape}, {type(myArr.shape)}') # 행렬이 아닌 렬행으로 보기
print(f'길이는? {myArr.size}') # 갯수
myArr

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원은? 1
구조는? (5,), <class 'tuple'>
길이는? 5


array([10, 56, 77, 23, 44])

In [9]:
# 2차원 리스트 => 넘파이 배열
myList2 = [[1,2,3], [10,20,30], [100, 200, 300]]
myList2

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]

In [10]:
myArr2 = np.array(myList2)
# len() 결과값이 2차원인 경우에는 행의수로 출력
print(myArr2, type(myArr2), len(myArr2))
print(f'차원은? {myArr2.ndim}') # 2차원 
print(f'구조는? {myArr2.shape}, {type(myArr2.shape)}') # 3,3의 2차원 구조
print(f'길이는? {myArr2.size}') # 9개의 원소
print(f'넘파이 배열은? {myArr2.shape[0]} 행 {myArr2.shape[1]}열')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원은? 2
구조는? (3, 3), <class 'tuple'>
길이는? 9
넘파이 배열은? 3 행 3열


In [11]:
# 2차원 리스트에서 각 행 수가 틀린 경우 테스트하기
# 넘파이 배열은?? 
myList3 = [[1,2], [10,20,30], [100,200,300,400,500]]
myList3, len(myList3)

([[1, 2], [10, 20, 30], [100, 200, 300, 400, 500]], 3)

In [12]:
#각행의 갯수가 틀린 경우 넘파이 배열로 생성하면 
# list([값...]) 형태로 삽입된다. 넘파이 배열 형태로 변환하려면 행의 갯수 맞추기 
myArr3 = np.array(myList3)
myArr3

C:\Users\TFG5076XG\anaconda3\envs\lima\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


array([list([1, 2]), list([10, 20, 30]), list([100, 200, 300, 400, 500])],
      dtype=object)

#리스트

In [13]:
# 넘파이 배열과 다르게 연산이 가능(산술연산)
listA = [10, 40, 50]
listB = [10, 40, 50]
# +인 경우 리스트간의 연결
listA + listB

[10, 40, 50, 10, 40, 50]

In [14]:
#리스트의 경우 *
#list * list의 경우에는 에러 발생(type에러)
listA * 2   #2번반복한다는 의미

[10, 40, 50, 10, 40, 50]

In [15]:
#넘파이 배열 간의 연산
#각 위치에 해당하는 요소간의 연산 차원, 갯수가 똑같아야함 
arrA = np.array([10, 40, 50])
arrB = np.array([5, 4, 3])
print(arrA + arrB)
print(arrA - arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB)
print(arrA % arrB)

[15 44 53]
[ 5 36 47]
[ 50 160 150]
[ 2.         10.         16.66666667]
[ 2 10 16]
[0 0 2]


In [16]:
#브로드캐스팅 
# 넘파이 배열 연산자 숫자가 들어감 
arrA #만약 arrA가 리스트라면 반복이 되겠지만 numpy배열로써 각각의 값에 2배
print(arrA)
print(arrA * 2)
print(arrA //3)

[10 40 50]
[ 20  80 100]
[ 3 13 16]


In [17]:
#리스트와 넘파이배열의 자료형 테스트
myList_c = ['홍길동', 100, 3.14, True, False]
#문자형, 정수, 실수, 논리형
myList_c, type(myList_c)#리스트라고 반환이 된다. 형이 그대로 유지된다,

(['홍길동', 100, 3.14, True, False], list)

In [18]:
#넘파이 배열의 구성 요소의 자료형 확인은?
#넘파이 배열명.dtype
#넘파이 배열은 1개의 형만 가지고 있으므로 데이터가 혼합되어 있는 경우 자동형변환이 이루어진다.
# 형태가 문자형으로 찍힌다. 문자열이 가장 큰 자료형으로써 문자열을 출력 
myArr_c = np.array(['홍길동', 100, 3.14, True, False])
myArr_c, type(myArr_c), myArr_c.dtype


(array(['홍길동', '100', '3.14', 'True', 'False'], dtype='<U32'),
 numpy.ndarray,
 dtype('<U32'))

In [19]:
# 정수랑 실수 혼합된 넘파이 배열 생성
#int와 float2가지가 혼용되어 있는데 float형식으로 변경됨
myArr_d = np.array([100, 3.14, 23.5 ,0]) 
myArr_d, type(myArr_d), myArr_d.dtype

(array([100.  ,   3.14,  23.5 ,   0.  ]), numpy.ndarray, dtype('float64'))

In [20]:
# 통계함수 적용하기
# my_Arr_d = 100, 3.14, 23.5, 0
# sum, mean, median, max, min
print(f'배열의 모든합은? {np.sum(myArr_d)}')
print(f'배열의 평균은? {np.mean(myArr_d)}')
print(f'배열의 중앙값은? {np.median(myArr_d)}')
print(f'배열의 최대값은? {np.max(myArr_d)}')
print(f'배열의 최소값은? {np.min(myArr_d)}')

배열의 모든합은? 126.64
배열의 평균은? 31.66
배열의 중앙값은? 13.32
배열의 최대값은? 100.0
배열의 최소값은? 0.0


# Numpy에서 제공하는 함수들 

```
np.ones(n), np.ones((x,y))
np.zeros(n), np.zeros((x,y))
np.empty(n), np.empty((x,y))
np.arange(start, end, step)

1차원에서 2차원으로 변경할 때 사용
reshape(x,y)
2차원에서 1차원으로 변경할 때 사용
flatten()
```

In [15]:
# 값이 1로 구성된 numpy 배열 생성
arr1 = np.ones(10)
# 기본값이 float 1.으로 만들어진다.
print(arr1)
arr1.dtype

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


dtype('float64')

In [25]:
# 1로 구성된 넘파이 배열 생성 => 정수형
arr2 = np.ones(10, dtype = int)
arr2, arr2.dtype

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), dtype('int32'))

In [26]:
# 1로 구성된 5행 2열 배열 생성 =>
arr3 = np.ones((5,2), dtype= int)
arr3, arr3.dtype, arr3.shape

(array([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]),
 dtype('int32'),
 (5, 2))

In [27]:
# 3행 3열 0으로 구성된 넘파이 배열
np.array([[0,0,0], [0,0,0], [0,0,0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
# 좀더 쉬운 방법으로 3행 3열 넘파이 배열 만들기
np.zeros((3,3), dtype= int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
# 1행 21열 nparray 배열 만들기
np.array(list(range(1,21)))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
# range 객체 => 리스트화 list(range()) => 넘파이 배열화
print(range(1,21), list(range(1,21)))
print(np.array(list(range(1,21))))
print('=' * 30)
arr6 = np.arange(1,21).reshape(4,5)
arr6

range(1, 21) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
arr7 = np.arange(50)
print(arr7.reshape(10, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [6]:
# 2차원에서 2차원도 변경 가능 
arr8 = arr7.reshape(5,10)
print(arr8)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [7]:
#2차원 => 1차원으로 변경
arr8.ndim, arr8.shape

(2, (5, 10))

In [8]:
# faltten()을 사용하면 1차원으로 변경 가능
# flatten은 1차원으로 변경하는 함수
arr8.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
# 기본적으로 arange문법 = np.arange(start, end, step)
# 1 ~ 100사이의 숫자로 만드는데 짝수로된 넘파이 배열 생성
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
# 홀수로 넘파이 배열 생성 
np.arange(1, 100, 2).reshape(25, 2), len(np.arange(1,100,2))

(array([[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19],
        [21, 23],
        [25, 27],
        [29, 31],
        [33, 35],
        [37, 39],
        [41, 43],
        [45, 47],
        [49, 51],
        [53, 55],
        [57, 59],
        [61, 63],
        [65, 67],
        [69, 71],
        [73, 75],
        [77, 79],
        [81, 83],
        [85, 87],
        [89, 91],
        [93, 95],
        [97, 99]]),
 50)

In [16]:
arr11 = np.arange(1, 31)
arr11, arr1.ndim # 1차원으로 만들어짐, reshape에 가끔 -1이 들어가는 경우가 발생

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 1)

In [17]:
arr12 = arr11.reshape(30,1)
arr12, arr12.ndim

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2)

In [18]:
# 1차원의 데이터인데 2차원으로 만드는 경우는 reshape에 음수를 넣어서 컬럼을 제거한다.
# reshape(-1, n) => 첫번째를 -1로 하면 2차원을 만들고 n개의 컬럼을 갖는다.
arr12 = arr11.reshape(-1,1)
arr12, arr12.ndim

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2)

In [19]:
# 2차원 배열에 2개의 컬럼
arr12 = arr11.reshape(-1, 2)
arr12, arr12.ndim

(array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]),
 2)

In [20]:
# 1, 20의 배열을 2차원의 4컬럼형태로 만들기
np.arange(1,21).reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [21]:
np.arange(1,21).reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])